### ISSUE TITLE
Does coldroute utilize formats?

### ISSUE THREAD

**Issue by james-t-g** [dhumphreys/cfwheels-coldroute#3]
I haven't dug through all of the code yet so I guess this is more of a question. Lately, I have been using formats like .pdf, .xls, .json, .ajax to help with code reuse. Does coldroute support the use of formats within the wheels framework?

**Comment by dhumphreys** [comment]
You can easily make a route, such as `get(pattern="documents/[key].[format]", to="documents##show")` and it _should_ work. I had some issues getting the built in `/[controller]/[action]/[key]` route to work with namespaced routes. There are some occasions in some of the code we are converting in our application where a path like this is still being hit: `/admin.items/index`. Wheels actually takes the path and splits it at the period to anticipate .html, .js, etc. This makes the comparison against `/admin` instead of the full path.

I had to disable this logic in my plugin overrides in order to get legacy path writing to work. This is less of an issue now that I changed `urlFor()` to actually look up the route path being asked for instead of defaulting to `/[controller]/[action]/[key]`.

Ideally, all routes created by `match()` should create an additional route with `.[format]` appended. And if nothing else, you could just pass `?format=pdf` or similar.
